### PR TITLE
Moves Handlers to custom namespace

### PR DESCRIPTION
**Pull request by sagikazarmark**
Moves handlers under `Handler` namespace.

BC breaking change

### CODE REVIEW

**Comment by stevewest** [comment]
I'd say that we don't need to worry about BC for now.

**Comment by stevewest** [comment]
I would add a note to the package's "unreleased" release to note the change though.

**Comment by sagikazarmark** [comment]
Done. @stevewest can you delete the development branch from packagist again?

**Comment by stevewest** [comment]
Done

**Pull request merged**
